# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: xenial
language: java
jdk: openjdk8
install: true # remove default
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq openjfx
script:
  - mvn -q clean install -Pno-network
  - jdk_switcher use openjdk7
  - cd core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
