# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: trusty
language: java
jdk: openjdk8
install: true # remove default
before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get build-dep libopenjfx-java
  - sudo apt-get --compile source libopenjfx-java
  - sudo dpkg -i libopenjfx-jni_8u60-b27-4~trusty1_amd64.deb
  - sudo dpkg -i libopenjfx-java_8u60-b27-4~trusty1_all.deb
  - sudo dpkg -i libopenjfx-java-doc_8u60-b27-4~trusty1_all.deb
  - sudo dpkg -i openjfx_8u60-b27-4~trusty1_amd64.deb
script:
  - mvn -q clean install -Pno-network
  - jdk_switcher use openjdk7
  - cd core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
