# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: trusty
language: java
jdk: openjdk9
install: true # remove default
before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo add-apt-repository ppa:webupd8team/java -y
  - sudo apt-get update
  - sudo apt-get install openjfx
script:
  - mvn -q clean install -Pno-network
  - jdk_switcher use openjdk7
  - cd core
  - mvn -q clean package -Pno-network

after_success:
  - cd ../core
  - mvn jacoco:report coveralls:report

notifications:
  irc:
    channels: "irc.freenode.net#bitcoinj"
    skip_join: true
